// <auto-generated />
using System;
using BadWolfQuiz.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BadWolfQuiz.Web.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    partial class QuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("BadWolfQuiz.Web.Models.AnswerContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AudioOnly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BottomCaption")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileContentType")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopCaption")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestionId");

                    b.ToTable("AnswerContentBlocks");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.GamePlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReconnectToken")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId", "Name")
                        .IsUnique();

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.GameQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BuzzOpenedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirstBuzzPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("QuizQuestionId");

                    b.ToTable("GameQuestions");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuizId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicCode")
                        .IsUnique();

                    b.HasIndex("QuizId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.PlayerBuzz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuzzOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamePlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameQuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ServerReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasFirst")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GamePlayerId");

                    b.HasIndex("GameQuestionId", "GamePlayerId")
                        .IsUnique();

                    b.ToTable("PlayerBuzzes");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.PlayerQuestionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("GamePlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameQuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GamePlayerId");

                    b.HasIndex("GameQuestionId", "GamePlayerId")
                        .IsUnique();

                    b.ToTable("PlayerQuestionResults");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.QuestionContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AudioOnly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BottomCaption")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileContentType")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopCaption")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestionId");

                    b.ToTable("QuestionContentBlocks");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseRandomWagerQuestions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.QuizCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizRoundId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuizRoundId", "SortOrder")
                        .IsUnique();

                    b.ToTable("QuizCategories");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuzzDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuzzModeOverride")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExcludeFromRandomWagerSelection")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeLimitSecondsOverride")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuizCategoryId", "RowIndex")
                        .IsUnique();

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.QuizRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultBuzzMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultTimeLimitSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RandomWagerQuestionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuizId", "SortOrder")
                        .IsUnique();

                    b.ToTable("QuizRounds");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.QuizRoundRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizRoundId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuizRoundId", "RowIndex")
                        .IsUnique();

                    b.ToTable("QuizRoundRows");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.AnswerContentBlock", b =>
                {
                    b.HasOne("BadWolfQuiz.Web.Models.QuizQuestion", "Question")
                        .WithMany("AnswerBlocks")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.GamePlayer", b =>
                {
                    b.HasOne("BadWolfQuiz.Web.Models.GameSession", "Session")
                        .WithMany("Players")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.GameQuestion", b =>
                {
                    b.HasOne("BadWolfQuiz.Web.Models.GameSession", "Session")
                        .WithMany("Questions")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadWolfQuiz.Web.Models.QuizQuestion", "QuizQuestion")
                        .WithMany()
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizQuestion");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.GameSession", b =>
                {
                    b.HasOne("BadWolfQuiz.Web.Models.Quiz", "Quiz")
                        .WithMany("Sessions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.PlayerBuzz", b =>
                {
                    b.HasOne("BadWolfQuiz.Web.Models.GamePlayer", "Player")
                        .WithMany()
                        .HasForeignKey("GamePlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadWolfQuiz.Web.Models.GameQuestion", "GameQuestion")
                        .WithMany("Buzzes")
                        .HasForeignKey("GameQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameQuestion");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.PlayerQuestionResult", b =>
                {
                    b.HasOne("BadWolfQuiz.Web.Models.GamePlayer", "Player")
                        .WithMany("Results")
                        .HasForeignKey("GamePlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadWolfQuiz.Web.Models.GameQuestion", "GameQuestion")
                        .WithMany("Results")
                        .HasForeignKey("GameQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameQuestion");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.QuestionContentBlock", b =>
                {
                    b.HasOne("BadWolfQuiz.Web.Models.QuizQuestion", "Question")
                        .WithMany("QuestionBlocks")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.QuizCategory", b =>
                {
                    b.HasOne("BadWolfQuiz.Web.Models.QuizRound", "Round")
                        .WithMany("Categories")
                        .HasForeignKey("QuizRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.QuizQuestion", b =>
                {
                    b.HasOne("BadWolfQuiz.Web.Models.QuizCategory", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("QuizCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.QuizRound", b =>
                {
                    b.HasOne("BadWolfQuiz.Web.Models.Quiz", "Quiz")
                        .WithMany("Rounds")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.QuizRoundRow", b =>
                {
                    b.HasOne("BadWolfQuiz.Web.Models.QuizRound", "Round")
                        .WithMany("Rows")
                        .HasForeignKey("QuizRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.GamePlayer", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.GameQuestion", b =>
                {
                    b.Navigation("Buzzes");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.GameSession", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.Quiz", b =>
                {
                    b.Navigation("Rounds");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.QuizCategory", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.QuizQuestion", b =>
                {
                    b.Navigation("AnswerBlocks");

                    b.Navigation("QuestionBlocks");
                });

            modelBuilder.Entity("BadWolfQuiz.Web.Models.QuizRound", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
