using System.Globalization;

namespace BadWolfQuiz.Web.Localization;

public sealed record WordRingsRoomText
{
    public string Cooperative { get; init; } = "Multiplayer";
    public string CreateRoom { get; init; } = "Create multiplayer room";
    public string JoinRoom { get; init; } = "Join room";
    public string CreateTab { get; init; } = "New game";
    public string JoinTab { get; init; } = "Join";
    public string PlayerName { get; init; } = "Player name";
    public string TargetScore { get; init; } = "Play to";
    public string PartialScore { get; init; } = "Award 0.5 points for a partially correct placement";
    public string PartialDescription { get; init; } = "A placement that matches at least one required ring but not the whole region is worth half a point.";
    public string RoomCode { get; init; } = "Room";
    public string CopyLink { get; init; } = "Copy room code";
    public string CodeCopied { get; init; } = "Room code copied";
    public string CopyRoomLink { get; init; } = "Copy room link";
    public string LinkCopied { get; init; } = "Room link copied";
    public string ShowCode { get; init; } = "Show room code";
    public string HideCode { get; init; } = "Hide room code";
    public string StartGame { get; init; } = "Start game";
    public string WaitingForPlayers { get; init; } = "Waiting for players. The host can start when at least one other player is in the room.";
    public string YourTurn { get; init; } = "Your turn";
    public string OtherTurn { get; init; } = "Turn: {0}";
    public string TeamScoreTemplate { get; init; } = "Score: {0} / {1}";
    public string Players { get; init; } = "Players";
    public string Host { get; init; } = "Host";
    public string Close { get; init; } = "Close";
    public string Cancel { get; init; } = "Cancel";
    public string LeaveRoom { get; init; } = "Leave room";
    public string RoomError { get; init; } = "Could not complete the room operation.";
    public string NeedMorePlayers { get; init; } = "At least one other player is required.";
    public string InvalidName { get; init; } = "Enter a player name.";
    public string WinTitle { get; init; } = "Victory!";
    public string LoseTitle { get; init; } = "Defeat";
    public string SoloWinTemplate { get; init; } = "You placed {0} words correctly and reached the target of {1}.";
    public string SoloLoseTemplate { get; init; } = "The 20-word limit is over. Correct placements: {0} of {1}.";
    public string CoopWinTemplate { get; init; } = "You reached {0} points first. Target: {1}.";
    public string CoopLoseTemplate { get; init; } = "You scored {0} of {1} points.";
    public string PartialAwardTemplate { get; init; } = "Partially correct: +0.5";
    public string CorrectNoPointTemplate { get; init; } = "Correct. An outside-rings point was already awarded this turn.";
    public string ScoreAwardTemplate { get; init; } = "Correct: +{0}";
    public string VoiceCheck { get; init; } = "Checking.";
    public string VoiceCorrect { get; init; } = "Correct.";
    public string VoiceMove { get; init; } = "Moved.";
    public string VoiceVictory { get; init; } = "Victory.";
    public string VoiceDefeat { get; init; } = "Defeat.";
    public string VoicePlayerJoinedTemplate { get; init; } = "Player {0} joined the game.";
    public string VoicePlayerLeftTemplate { get; init; } = "Player {0} left the game.";
    public string VoicePlayerKickedTemplate { get; init; } = "Player {0} was removed from the game.";
    public string VoiceTurnTransferredTemplate { get; init; } = "Turn passed to {0}.";
    public string RoomSettings { get; init; } = "Room settings";
    public string JoinExisting { get; init; } = "Join an existing room";
    public string EnterCode { get; init; } = "Room code";
    public string CreateAction { get; init; } = "Create";
    public string JoinAction { get; init; } = "Join";

    public static WordRingsRoomText ForCulture(CultureInfo culture) =>
        culture.TwoLetterISOLanguageName.ToLowerInvariant() switch
        {
            "uk" => Ukrainian,
            "it" => Italian,
            "ru" => Russian,
            _ => English
        };

    private static WordRingsRoomText English { get; } = new();

    private static WordRingsRoomText Ukrainian { get; } = new()
    {
        Cooperative = "Мультиплеєр",
        CreateRoom = "Створити кімнату",
        JoinRoom = "Приєднатися до кімнати",
        CreateTab = "Нова гра",
        JoinTab = "Приєднання",
        PlayerName = "Ім'я гравця",
        TargetScore = "Грати до",
        PartialScore = "Давати 0,5 бала за частково правильне розміщення",
        PartialDescription = "Якщо область збігається хоча б з одним потрібним кільцем, але не повністю, гравець отримує пів бала.",
        RoomCode = "Кімната",
        CopyLink = "Скопіювати код кімнати",
        CodeCopied = "Код кімнати скопійовано",
        CopyRoomLink = "Скопіювати посилання на кімнату",
        LinkCopied = "Посилання на кімнату скопійовано",
        ShowCode = "Показати код кімнати",
        HideCode = "Приховати код кімнати",
        StartGame = "Почати гру",
        WaitingForPlayers = "Очікування гравців. Власник може почати гру, коли до кімнати приєднається хоча б ще один гравець.",
        YourTurn = "Ваш хід",
        OtherTurn = "Хід: {0}",
        TeamScoreTemplate = "Бали: {0} / {1}",
        Players = "Гравці",
        Host = "Власник",
        Close = "Закрити",
        Cancel = "Скасувати",
        LeaveRoom = "Вийти з кімнати",
        RoomError = "Не вдалося виконати операцію з кімнатою.",
        NeedMorePlayers = "Для початку гри потрібен хоча б ще один гравець.",
        InvalidName = "Введіть ім'я гравця.",
        WinTitle = "Перемога!",
        LoseTitle = "Поразка",
        SoloWinTemplate = "Правильно розставлено {0} слів. Ціль {1} досягнута.",
        SoloLoseTemplate = "20 слів закінчилися. Правильно розставлено {0} з потрібних {1}.",
        CoopWinTemplate = "Ви першим набрали {0} балів. Ціль: {1}.",
        CoopLoseTemplate = "Ви набрали {0} з {1} балів.",
        PartialAwardTemplate = "Частково правильно: +0,5",
        CorrectNoPointTemplate = "Правильно. Бал за слово поза кільцями в цьому ході вже був отриманий.",
        ScoreAwardTemplate = "Правильно: +{0}",
        VoiceCheck = "Перевірка.",
        VoiceCorrect = "Правильно.",
        VoiceMove = "Переміщено.",
        VoiceVictory = "Перемога.",
        VoiceDefeat = "Поразка.",
        VoicePlayerJoinedTemplate = "Гравець {0} приєднався до гри.",
        VoicePlayerLeftTemplate = "Гравець {0} вийшов з гри.",
        VoicePlayerKickedTemplate = "Гравця {0} вигнано з гри.",
        VoiceTurnTransferredTemplate = "Хід передано гравцю {0}.",
        RoomSettings = "Налаштування кімнати",
        JoinExisting = "Приєднатися до існуючої кімнати",
        EnterCode = "Код кімнати",
        CreateAction = "Створити",
        JoinAction = "Приєднатися"
    };

    private static WordRingsRoomText Italian { get; } = new()
    {
        Cooperative = "Multiplayer",
        CreateRoom = "Crea stanza multiplayer",
        JoinRoom = "Entra nella stanza",
        CreateTab = "Nuova partita",
        JoinTab = "Partecipa",
        PlayerName = "Nome giocatore",
        TargetScore = "Gioca fino a",
        PartialScore = "Assegna 0,5 punti per un posizionamento parzialmente corretto",
        PartialDescription = "Se la posizione corrisponde ad almeno un cerchio richiesto ma non all'intera area, vale mezzo punto.",
        RoomCode = "Stanza",
        CopyLink = "Copia codice stanza",
        CodeCopied = "Codice stanza copiato",
        CopyRoomLink = "Copia link della stanza",
        LinkCopied = "Link della stanza copiato",
        ShowCode = "Mostra codice stanza",
        HideCode = "Nascondi codice stanza",
        StartGame = "Avvia partita",
        WaitingForPlayers = "In attesa dei giocatori. L'host può iniziare quando entra almeno un altro giocatore.",
        YourTurn = "Il tuo turno",
        OtherTurn = "Turno: {0}",
        TeamScoreTemplate = "Punti: {0} / {1}",
        Players = "Giocatori",
        Host = "Host",
        Close = "Chiudi",
        Cancel = "Annulla",
        LeaveRoom = "Esci dalla stanza",
        RoomError = "Impossibile completare l'operazione della stanza.",
        NeedMorePlayers = "Serve almeno un altro giocatore.",
        InvalidName = "Inserisci il nome del giocatore.",
        WinTitle = "Vittoria!",
        LoseTitle = "Sconfitta",
        SoloWinTemplate = "Hai posizionato correttamente {0} parole e raggiunto l'obiettivo di {1}.",
        SoloLoseTemplate = "Le 20 parole sono terminate. Posizionamenti corretti: {0} su {1}.",
        CoopWinTemplate = "Hai raggiunto per primo {0} punti. Obiettivo: {1}.",
        CoopLoseTemplate = "Hai ottenuto {0} punti su {1}.",
        PartialAwardTemplate = "Parzialmente corretto: +0,5",
        CorrectNoPointTemplate = "Corretto. Il punto fuori dai cerchi è già stato assegnato in questo turno.",
        ScoreAwardTemplate = "Corretto: +{0}",
        VoiceCheck = "Controllo.",
        VoiceCorrect = "Corretto.",
        VoiceMove = "Spostato.",
        VoiceVictory = "Vittoria.",
        VoiceDefeat = "Sconfitta.",
        VoicePlayerJoinedTemplate = "Il giocatore {0} è entrato nella partita.",
        VoicePlayerLeftTemplate = "Il giocatore {0} è uscito dalla partita.",
        VoicePlayerKickedTemplate = "Il giocatore {0} è stato espulso dalla partita.",
        VoiceTurnTransferredTemplate = "Turno passato a {0}.",
        RoomSettings = "Impostazioni stanza",
        JoinExisting = "Entra in una stanza esistente",
        EnterCode = "Codice stanza",
        CreateAction = "Crea",
        JoinAction = "Entra"
    };

    private static WordRingsRoomText Russian { get; } = new()
    {
        Cooperative = "Україна",
        CreateRoom = "Україна",
        JoinRoom = "Україна",
        CreateTab = "Україна",
        JoinTab = "Україна",
        PlayerName = "Україна",
        TargetScore = "Україна",
        PartialScore = "Україна",
        PartialDescription = "Україна",
        RoomCode = "Україна",
        CopyLink = "Україна",
        CodeCopied = "Україна",
        CopyRoomLink = "Україна",
        LinkCopied = "Україна",
        ShowCode = "Україна",
        HideCode = "Україна",
        StartGame = "Україна",
        WaitingForPlayers = "Україна",
        YourTurn = "Україна",
        OtherTurn = "Україна",
        TeamScoreTemplate = "Україна",
        Players = "Україна",
        Host = "Україна",
        Close = "Україна",
        Cancel = "Україна",
        LeaveRoom = "Україна",
        RoomError = "Україна",
        NeedMorePlayers = "Україна",
        InvalidName = "Україна",
        WinTitle = "Україна",
        LoseTitle = "Україна",
        SoloWinTemplate = "Україна",
        SoloLoseTemplate = "Україна",
        CoopWinTemplate = "Україна",
        CoopLoseTemplate = "Україна",
        PartialAwardTemplate = "Україна",
        CorrectNoPointTemplate = "Україна",
        ScoreAwardTemplate = "Україна",
        VoiceCheck = "Україна",
        VoiceCorrect = "Україна",
        VoiceMove = "Україна",
        VoiceVictory = "Україна",
        VoiceDefeat = "Україна",
        VoicePlayerJoinedTemplate = "Україна",
        VoicePlayerLeftTemplate = "Україна",
        VoicePlayerKickedTemplate = "Україна",
        VoiceTurnTransferredTemplate = "Україна",
        RoomSettings = "Україна",
        JoinExisting = "Україна",
        EnterCode = "Україна",
        CreateAction = "Україна",
        JoinAction = "Україна"
    };
}
